// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDmP-tFKBnE2vlNDUbql3XP2ZA6H5FTa4',
    appId: '1:1025246402551:web:04fc3e9a090d03ce9f80f2',
    messagingSenderId: '1025246402551',
    projectId: 'biddy-45c49',
    authDomain: 'biddy-45c49.firebaseapp.com',
    databaseURL: 'https://biddy-45c49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biddy-45c49.appspot.com',
    measurementId: 'G-HNYV051TT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-rzeVOyIvMr2yhEAaxdx2YMVufFtXDM',
    appId: '1:1025246402551:android:a63f4208693f354d9f80f2',
    messagingSenderId: '1025246402551',
    projectId: 'biddy-45c49',
    databaseURL: 'https://biddy-45c49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biddy-45c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbjzYDD8SDiy1kLbi1f3lnQhVgX1F9V6U',
    appId: '1:1025246402551:ios:36838b9a3535dda49f80f2',
    messagingSenderId: '1025246402551',
    projectId: 'biddy-45c49',
    databaseURL: 'https://biddy-45c49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biddy-45c49.appspot.com',
    androidClientId: '1025246402551-dj19kjqitgu7d1nfqol87ncsbfjbbsjd.apps.googleusercontent.com',
    iosClientId: '1025246402551-2q54i1krefd4m530pn48itkea4h3q2s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.biddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbjzYDD8SDiy1kLbi1f3lnQhVgX1F9V6U',
    appId: '1:1025246402551:ios:36838b9a3535dda49f80f2',
    messagingSenderId: '1025246402551',
    projectId: 'biddy-45c49',
    databaseURL: 'https://biddy-45c49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biddy-45c49.appspot.com',
    androidClientId: '1025246402551-dj19kjqitgu7d1nfqol87ncsbfjbbsjd.apps.googleusercontent.com',
    iosClientId: '1025246402551-2q54i1krefd4m530pn48itkea4h3q2s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.biddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDmP-tFKBnE2vlNDUbql3XP2ZA6H5FTa4',
    appId: '1:1025246402551:web:04ed51b28a9869189f80f2',
    messagingSenderId: '1025246402551',
    projectId: 'biddy-45c49',
    authDomain: 'biddy-45c49.firebaseapp.com',
    databaseURL: 'https://biddy-45c49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biddy-45c49.appspot.com',
    measurementId: 'G-H7ZRHF2G8V',
  );

}